package com.mycompany.hiChatJpa.view.pages.home;

import javax.swing.JPanel;

/**
 *
 * @author gatog
 */
public class DashboardPane extends javax.swing.JPanel {

    private String currentStatus;
    private final JPanel contentPane;
    
    
    /**
     * Creates new form DashboardPane
     * @param panel
     */
    public DashboardPane(JPanel panel) {
        contentPane = panel;
        initComponents();
        
        this.currentStatus = "DISCOVER";
        discoverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purple-discover.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPane = new javax.swing.JPanel();
        discoverLabel = new javax.swing.JLabel();
        matchLabel = new javax.swing.JLabel();
        chatLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();

        setOpaque(false);

        backgroundPane.setBackground(new java.awt.Color(255, 153, 153));
        backgroundPane.setOpaque(false);
        backgroundPane.setPreferredSize(new java.awt.Dimension(400, 60));
        backgroundPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        discoverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-discover.png"))); // NOI18N
        discoverLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        discoverLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discoverLabelMouseClicked(evt);
            }
        });
        backgroundPane.add(discoverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, 40));

        matchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-heart.png"))); // NOI18N
        matchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        matchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matchLabelMouseClicked(evt);
            }
        });
        backgroundPane.add(matchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 40));

        chatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-chat.png"))); // NOI18N
        chatLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabelMouseClicked(evt);
            }
        });
        backgroundPane.add(chatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 40));

        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-profile.png"))); // NOI18N
        profileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });
        backgroundPane.add(profileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void discoverLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discoverLabelMouseClicked
        if (!"DISCOVER".equals(currentStatus)) {
            disableAll();
            discoverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purple-discover.png")));
            currentStatus = "DISCOVER";
        }
    }//GEN-LAST:event_discoverLabelMouseClicked

    private void matchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchLabelMouseClicked
        if (!"MATCH".equals(currentStatus)) {
            disableAll();
            matchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purple-heart.png")));
            currentStatus = "MATCH";
        }
    }//GEN-LAST:event_matchLabelMouseClicked

    private void chatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabelMouseClicked
        if (!"CHAT".equals(currentStatus)) {
            disableAll();
            chatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purple-chat.png")));
            currentStatus = "CHAT";
        }
    }//GEN-LAST:event_chatLabelMouseClicked

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
        if (!"PROFILE".equals(currentStatus)) {
            disableAll();
            profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purple-profile.png")));
            currentStatus = "PROFILE";
        }
    }//GEN-LAST:event_profileLabelMouseClicked

    /**
     * metodo de utileria que nos permite despintar las opciones fuera de foco
     */
    private void disableAll() {
        discoverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-discover.png")));
        matchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-heart.png")));
        chatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-chat.png")));
        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grey-profile.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPane;
    private javax.swing.JLabel chatLabel;
    private javax.swing.JLabel discoverLabel;
    private javax.swing.JLabel matchLabel;
    private javax.swing.JLabel profileLabel;
    // End of variables declaration//GEN-END:variables
}
