package com.mycompany.hiChatJpa.view.pages.home;

import com.mycompany.hiChatJpa.dto.UsuarioPerfilDTO;
import com.mycompany.hiChatJpa.entitys.TipoInteraccion;
import com.mycompany.hiChatJpa.exceptions.ServiceException;
import com.mycompany.hiChatJpa.service.IUsuarioService;
import com.mycompany.hiChatJpa.service.impl.UsuarioService;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Iterator;
import java.util.NoSuchElementException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gatog
 */
public class DiscoverPane extends javax.swing.JPanel {

    private UsuarioPerfilDTO currentUser;
    private UsuarioPerfilDTO loggedUser;
    private final IUsuarioService USUARIO_SERVICE;
    private Iterator<UsuarioPerfilDTO> PRETENDIENTES;

    /**
     * Creates new form LoginPane
     *
     * @param panel
     * @param usuario
     */
    public DiscoverPane(JPanel panel, UsuarioPerfilDTO usuario) {
        initComponents();        
        this.loggedUser = usuario;
        this.USUARIO_SERVICE = new UsuarioService();
        try {
            this.PRETENDIENTES = USUARIO_SERVICE.mostrarPretendientes(loggedUser.getIdUsuario()).iterator();
            loadNext();
        } catch (ServiceException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "soo sorry :(", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        likePane = new com.mycompany.hiChatJpa.view.components.PanelRound();
        heartLabel = new javax.swing.JLabel();
        dislikePanel = new com.mycompany.hiChatJpa.view.components.PanelRound();
        dislikeLabel = new javax.swing.JLabel();
        userCard = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        userBiography = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 16, 34));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        likePane.setBackground(new java.awt.Color(55, 65, 81));
        likePane.setRoundBottomLeft(360);
        likePane.setRoundBottomRight(360);
        likePane.setRoundTopLeft(360);
        likePane.setRoundTopRight(360);
        likePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heartLabel.setBackground(new java.awt.Color(55, 65, 81));
        heartLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue-heart.png"))); // NOI18N
        heartLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        heartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heartLabelMouseClicked(evt);
            }
        });
        likePane.add(heartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        add(likePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 70, 70));

        dislikePanel.setBackground(new java.awt.Color(55, 65, 81));
        dislikePanel.setRoundBottomLeft(360);
        dislikePanel.setRoundBottomRight(360);
        dislikePanel.setRoundTopLeft(360);
        dislikePanel.setRoundTopRight(360);
        dislikePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dislikeLabel.setBackground(new java.awt.Color(55, 65, 81));
        dislikeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dislikeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/red-cancel.png"))); // NOI18N
        dislikeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dislikeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dislikeLabelMouseClicked(evt);
            }
        });
        dislikePanel.add(dislikeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        add(dislikePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 70, 70));

        userCard.setBackground(new java.awt.Color(0, 0, 0));

        username.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("name");

        userBiography.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        userBiography.setForeground(new java.awt.Color(255, 255, 255));
        userBiography.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userBiography.setText("biography");

        javax.swing.GroupLayout userCardLayout = new javax.swing.GroupLayout(userCard);
        userCard.setLayout(userCardLayout);
        userCardLayout.setHorizontalGroup(
            userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCardLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCardLayout.createSequentialGroup()
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userCardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(userBiography, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        userCardLayout.setVerticalGroup(
            userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCardLayout.createSequentialGroup()
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCardLayout.createSequentialGroup()
                    .addContainerGap(327, Short.MAX_VALUE)
                    .addComponent(userBiography, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        add(userCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 400));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo que permite dar like ala vez que carga al siguente pretendiente
     *
     * @param evt
     */
    private void heartLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartLabelMouseClicked
        try {
            USUARIO_SERVICE.registrarInteraccion(loggedUser.getIdUsuario(), currentUser.getIdUsuario(), TipoInteraccion.ME_GUSTA);
        } catch (ServiceException ex) {
            JOptionPane.showMessageDialog(null, "that action cant be done rn", "soo sorry :(", JOptionPane.INFORMATION_MESSAGE);
        }
        loadNext();
    }//GEN-LAST:event_heartLabelMouseClicked

    /**
     * metodo que permite dar dislike ala vez que carga al siguente pretendiente
     *
     * @param evt
     */
    private void dislikeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dislikeLabelMouseClicked
        try {
            USUARIO_SERVICE.registrarInteraccion(loggedUser.getIdUsuario(), currentUser.getIdUsuario(), TipoInteraccion.NO_ME_INTERESA);
        } catch (ServiceException ex) {
            JOptionPane.showMessageDialog(null, "that action cant be done rn", "soo sorry :(", JOptionPane.INFORMATION_MESSAGE);
        }
        loadNext();
    }//GEN-LAST:event_dislikeLabelMouseClicked

    /**
     * metodo de utileria que cambia la tarjeta de presentacion de los
     * pretendientes
     */
    private void loadNext() {
        try {
            this.currentUser = PRETENDIENTES.next();
            this.username.setText(currentUser.getNombre() + " " + currentUser.getApellidoPaterno());
            this.userBiography.setText(currentUser.getBiografia());
            changeImg();
        } catch (NoSuchElementException ex) {
            this.userCard.setVisible(false);
            this.dislikePanel.setVisible(false);
            this.likePane.setVisible(false);
        }
    }

    /**
     * metodo de utileria que cambia la foto del perfil mostrado
     */
    private void changeImg() {
        String rutaFoto = currentUser.getUrlFotoPerfil();

        try {
            ImageIcon iconOriginal;
            if (rutaFoto.startsWith("/")) {
                java.net.URL iconURL = getClass().getResource(rutaFoto);
                if (iconURL == null) {
                    System.err.println("⚠️ No se encontró el recurso: " + rutaFoto);
                    cargarImagenPorDefecto();
                    return;
                }
                iconOriginal = new ImageIcon(iconURL);

            } else if (rutaFoto.startsWith("http://") || rutaFoto.startsWith("https://")) {
                try {
                    URL url = new URL(rutaFoto);
                    iconOriginal = new ImageIcon(url);
                    if (iconOriginal.getImageLoadStatus() != java.awt.MediaTracker.COMPLETE) {
                        System.err.println("⚠️ Error al cargar imagen desde URL");
                        cargarImagenPorDefecto();
                        return;
                    }

                } catch (MalformedURLException e) {
                    cargarImagenPorDefecto();
                    return;
                }
            } else {
                iconOriginal = new ImageIcon(rutaFoto);
            }

            // Redimensionar la imagen
            int maxAncho = 380 - 20;
            int maxAlto = 358 - 20;

            int anchoOriginal = iconOriginal.getIconWidth();
            int altoOriginal = iconOriginal.getIconHeight();

            if (anchoOriginal <= 0 || altoOriginal <= 0) {
                cargarImagenPorDefecto();
                return;
            }

            double escalaAncho = (double) maxAncho / anchoOriginal;
            double escalaAlto = (double) maxAlto / altoOriginal;
            double escala = Math.min(escalaAncho, escalaAlto);

            int nuevoAncho = (int) (anchoOriginal * escala);
            int nuevoAlto = (int) (altoOriginal * escala);

            Image imgEscalada = iconOriginal.getImage().getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);

            imgLabel.setIcon(new ImageIcon(imgEscalada));
            imgLabel.setText("");

        } catch (Exception e) {
            cargarImagenPorDefecto();
        }
    }

    /**
     * Carga la imagen por defecto cuando falla la carga de la foto del usuario
     */
    private void cargarImagenPorDefecto() {
        try {
            java.net.URL iconURL = getClass().getResource("/icons/default-picture.png");

            if (iconURL != null) {
                ImageIcon iconOriginal = new ImageIcon(iconURL);
                int maxAncho = 380 - 20;
                int maxAlto = 358 - 20;

                Image imgEscalada = iconOriginal.getImage().getScaledInstance(maxAncho, maxAlto, Image.SCALE_SMOOTH);

                imgLabel.setIcon(new ImageIcon(imgEscalada));
                imgLabel.setText("");
            } else {
                imgLabel.setIcon(null);
                imgLabel.setText("Sin foto");
            }

        } catch (Exception e) {
            imgLabel.setIcon(null);
            imgLabel.setText("Sin foto");
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dislikeLabel;
    private com.mycompany.hiChatJpa.view.components.PanelRound dislikePanel;
    private javax.swing.JLabel heartLabel;
    private javax.swing.JLabel imgLabel;
    private com.mycompany.hiChatJpa.view.components.PanelRound likePane;
    private javax.swing.JLabel userBiography;
    private javax.swing.JPanel userCard;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
