package com.mycompany.hiChatJpa.view.pages.home;

import com.mycompany.hiChatJpa.dto.MatchDTO;
import com.mycompany.hiChatJpa.dto.UsuarioPerfilDTO;
import com.mycompany.hiChatJpa.service.IUsuarioService;
import com.mycompany.hiChatJpa.service.impl.UsuarioService;
import com.mycompany.hiChatJpa.view.components.MatchRegistroPanel;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author gatog
 */
public class MatchPane extends javax.swing.JPanel {

    private final UsuarioPerfilDTO loggedUser;
    private final IUsuarioService USUARIO_SERVICE;

    /**
     * Creates new form LoginPane
     *
     * @param panel
     * @param usuario
     */
    public MatchPane(JPanel panel, UsuarioPerfilDTO usuario) {
        this.loggedUser = usuario;
        this.USUARIO_SERVICE = new UsuarioService();
        initComponents();

        panelLista = new JPanel(new GridLayout(0, 1));
        
        cargarMatches();
        
        JPanel container = new JPanel(new BorderLayout());
        container.add(panelLista, BorderLayout.NORTH);
        JScrollPane scrollPane = new JScrollPane(container);
        scrollPane.getVerticalScrollBar().setUnitIncrement(15);
        add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLista = new javax.swing.JPanel();

        setBackground(new java.awt.Color(22, 16, 34));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new java.awt.BorderLayout());

        panelLista.setOpaque(false);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        add(panelLista, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarMatches() {        
        List<MatchDTO> matches = USUARIO_SERVICE.mostrarMatches(loggedUser.getIdUsuario());
        if(matches == null) {
            return;
        }
        
        matches.forEach(p -> {
            panelLista.add(new MatchRegistroPanel(p));
        });
         panelLista.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelLista;
    // End of variables declaration//GEN-END:variables
}
