
package com.mycompany.hiChatJpa.view.pages.home;

import com.mycompany.hiChatJpa.view.MainFrame;

/**
 *
 * @author gatog
 */
public class ProfilePane extends javax.swing.JPanel {

    
    /**
     * Creates new form LoginPane
     * @param frame
     */
    public ProfilePane(MainFrame frame) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleLabel = new javax.swing.JLabel();
        textFieldPanel1 = new com.mycompany.hiChatJpa.view.components.TextFieldPanel();
        panelRound1 = new com.mycompany.hiChatJpa.view.components.PanelRound();

        setBackground(new java.awt.Color(22, 16, 34));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("nombre perfil");
        add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, -1));
        add(textFieldPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        panelRound1.setRoundBottomLeft(360);
        panelRound1.setRoundBottomRight(360);
        panelRound1.setRoundTopLeft(360);
        panelRound1.setRoundTopRight(360);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 270, 220));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.hiChatJpa.view.components.PanelRound panelRound1;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel textFieldPanel1;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
}
