
package com.mycompany.hiChatJpa.view.pages.signin;

import com.mycompany.hiChatJpa.view.MainFrame;

/**
 *
 * @author gatog
 */
public class SigninDatePane extends javax.swing.JPanel {

    private final MainFrame FATHER;
    
    /**
     * Creates new form SigninPane
     * @param frame
     */
    public SigninDatePane(MainFrame frame) {
        this.FATHER  =  frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPane = new javax.swing.JPanel();
        headerPane = new javax.swing.JPanel();
        tittleLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JLabel();
        stepsPane = new javax.swing.JPanel();
        coloredPane1 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        coloredPane2 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        coloredPane3 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        coloredPane4 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        coloredPane5 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        usernameLabel = new javax.swing.JLabel();
        createAccountLabel = new javax.swing.JLabel();
        continuePane = new com.mycompany.hiChatJpa.view.components.PanelRound();
        continueLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        logInLabel = new javax.swing.JLabel();
        dataPane = new javax.swing.JPanel();
        usernameLabel1 = new javax.swing.JLabel();
        textFieldPanel1 = new com.mycompany.hiChatJpa.view.components.TextFieldPanel();
        usernameLabel2 = new javax.swing.JLabel();
        textFieldPanel2 = new com.mycompany.hiChatJpa.view.components.TextFieldPanel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        backgroundPane.setBackground(new java.awt.Color(22, 16, 34));

        headerPane.setBackground(new java.awt.Color(51, 153, 255));
        headerPane.setOpaque(false);
        headerPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tittleLabel.setText("HiChat!");
        headerPane.add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 18, 240, 20));

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purple-arrow-32px.png"))); // NOI18N
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });
        headerPane.add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 30));

        stepsPane.setBackground(new java.awt.Color(0, 0, 0));
        stepsPane.setOpaque(false);
        stepsPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coloredPane1.setBackground(new java.awt.Color(108, 43, 238));
        coloredPane1.setRoundBottomLeft(15);
        coloredPane1.setRoundBottomRight(15);
        coloredPane1.setRoundTopLeft(15);
        coloredPane1.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane1Layout = new javax.swing.GroupLayout(coloredPane1);
        coloredPane1.setLayout(coloredPane1Layout);
        coloredPane1Layout.setHorizontalGroup(
            coloredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane1Layout.setVerticalGroup(
            coloredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, 40, 10));

        coloredPane2.setBackground(new java.awt.Color(108, 43, 238));
        coloredPane2.setRoundBottomLeft(15);
        coloredPane2.setRoundBottomRight(15);
        coloredPane2.setRoundTopLeft(15);
        coloredPane2.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane2Layout = new javax.swing.GroupLayout(coloredPane2);
        coloredPane2.setLayout(coloredPane2Layout);
        coloredPane2Layout.setHorizontalGroup(
            coloredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane2Layout.setVerticalGroup(
            coloredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 40, 10));

        coloredPane3.setBackground(new java.awt.Color(47, 35, 72));
        coloredPane3.setRoundBottomLeft(15);
        coloredPane3.setRoundBottomRight(15);
        coloredPane3.setRoundTopLeft(15);
        coloredPane3.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane3Layout = new javax.swing.GroupLayout(coloredPane3);
        coloredPane3.setLayout(coloredPane3Layout);
        coloredPane3Layout.setHorizontalGroup(
            coloredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane3Layout.setVerticalGroup(
            coloredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 15, 40, 10));

        coloredPane4.setBackground(new java.awt.Color(47, 35, 72));
        coloredPane4.setRoundBottomLeft(15);
        coloredPane4.setRoundBottomRight(15);
        coloredPane4.setRoundTopLeft(15);
        coloredPane4.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane4Layout = new javax.swing.GroupLayout(coloredPane4);
        coloredPane4.setLayout(coloredPane4Layout);
        coloredPane4Layout.setHorizontalGroup(
            coloredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane4Layout.setVerticalGroup(
            coloredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, 40, 10));

        coloredPane5.setBackground(new java.awt.Color(47, 35, 72));
        coloredPane5.setRoundBottomLeft(15);
        coloredPane5.setRoundBottomRight(15);
        coloredPane5.setRoundTopLeft(15);
        coloredPane5.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane5Layout = new javax.swing.GroupLayout(coloredPane5);
        coloredPane5.setLayout(coloredPane5Layout);
        coloredPane5Layout.setHorizontalGroup(
            coloredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane5Layout.setVerticalGroup(
            coloredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 15, 40, 10));

        usernameLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Step 2 of 5");
        stepsPane.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 20));

        createAccountLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        createAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        createAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountLabel.setText("Welcome to HiChat!");

        continuePane.setBackground(new java.awt.Color(108, 43, 238));
        continuePane.setRoundBottomLeft(25);
        continuePane.setRoundBottomRight(25);
        continuePane.setRoundTopLeft(25);
        continuePane.setRoundTopRight(25);

        continueLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        continueLabel.setForeground(new java.awt.Color(255, 255, 255));
        continueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continueLabel.setText("Continue");
        continueLabel.setToolTipText("");
        continueLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout continuePaneLayout = new javax.swing.GroupLayout(continuePane);
        continuePane.setLayout(continuePaneLayout);
        continuePaneLayout.setHorizontalGroup(
            continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(continueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );
        continuePaneLayout.setVerticalGroup(
            continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(continueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        messageLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageLabel.setText("You already have an account ?");
        messageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logInLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        logInLabel.setForeground(new java.awt.Color(189, 147, 249));
        logInLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logInLabel.setText("Log In");
        logInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInLabelMouseClicked(evt);
            }
        });

        dataPane.setBackground(new java.awt.Color(51, 0, 153));
        dataPane.setOpaque(false);
        dataPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel1.setText("last name");
        dataPane.add(usernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 360, 20));
        dataPane.add(textFieldPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        usernameLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        usernameLabel2.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel2.setText("your birthday");
        dataPane.add(usernameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 360, 20));
        dataPane.add(textFieldPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        javax.swing.GroupLayout backgroundPaneLayout = new javax.swing.GroupLayout(backgroundPane);
        backgroundPane.setLayout(backgroundPaneLayout);
        backgroundPaneLayout.setHorizontalGroup(
            backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPaneLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(continuePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundPaneLayout.createSequentialGroup()
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stepsPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        backgroundPaneLayout.setVerticalGroup(
            backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPaneLayout.createSequentialGroup()
                .addComponent(headerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAccountLabel)
                .addGap(27, 27, 27)
                .addComponent(dataPane, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(continuePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        FATHER.showView(MainFrame.SIGNIN_VIEW);
    }//GEN-LAST:event_returnButtonMouseClicked

    private void logInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInLabelMouseClicked
        FATHER.showView(MainFrame.LOGIN_VIEW);
    }//GEN-LAST:event_logInLabelMouseClicked

    private void continueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLabelMouseClicked
        FATHER.showView(MainFrame.SIGNIN_PASSWORD_VIEW
        );
    }//GEN-LAST:event_continueLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPane;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane1;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane2;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane3;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane4;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane5;
    private javax.swing.JLabel continueLabel;
    private com.mycompany.hiChatJpa.view.components.PanelRound continuePane;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JPanel dataPane;
    private javax.swing.JPanel headerPane;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel returnButton;
    private javax.swing.JPanel stepsPane;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel textFieldPanel1;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel textFieldPanel2;
    private javax.swing.JLabel tittleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JLabel usernameLabel2;
    // End of variables declaration//GEN-END:variables
}
