package com.mycompany.hiChatJpa.view.pages.login;

import com.mycompany.hiChatJpa.entitys.Usuario;
import com.mycompany.hiChatJpa.service.IUsuarioService;
import com.mycompany.hiChatJpa.service.impl.UsuarioService;
import com.mycompany.hiChatJpa.view.MainFrame;
import com.mycompany.hiChatJpa.view.components.TextFieldPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author gatog
 */
public class LoginPane extends javax.swing.JPanel {

    private final MainFrame FATHER;
    private final IUsuarioService USUARIO_SERVICE;

    /**
     * Creates new form LoginPane
     *
     * @param frame
     */
    public LoginPane(MainFrame frame) {
        this.FATHER = frame;
        this.USUARIO_SERVICE = new UsuarioService();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPane = new javax.swing.JPanel();
        tittleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        dataPane = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        userInputPane = new TextFieldPanel(TextFieldPanel.EMAIL_REGEX, "invalid type of email");
        passwordLabel = new javax.swing.JLabel();
        passwordInputPane = new com.mycompany.hiChatJpa.view.components.TextFieldPanel();
        forgotPasswordLabel = new javax.swing.JLabel();
        actionsPane = new javax.swing.JPanel();
        signInPane = new com.mycompany.hiChatJpa.view.components.PanelRound();
        signInLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        signUpLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        backgroundPane.setBackground(new java.awt.Color(22, 16, 34));
        backgroundPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("HiChat!");
        backgroundPane.add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, -1));

        descriptionLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(204, 204, 204));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("Welcome to hichat get started or login to continue");
        backgroundPane.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 20));

        dataPane.setOpaque(false);
        dataPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel.setText("Email");
        dataPane.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 360, 20));

        userInputPane.setMessage("enter your email");
        dataPane.add(userInputPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordLabel.setText("Password");
        dataPane.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 85, 360, 20));

        passwordInputPane.setMessage("enter your password");
        dataPane.add(passwordInputPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        forgotPasswordLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(189, 147, 249));
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forgotPasswordLabel.setText("forgot password? ");
        forgotPasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });
        dataPane.add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 130, 20));

        backgroundPane.add(dataPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 190));

        actionsPane.setOpaque(false);
        actionsPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInPane.setBackground(new java.awt.Color(108, 43, 238));
        signInPane.setRoundBottomLeft(25);
        signInPane.setRoundBottomRight(25);
        signInPane.setRoundTopLeft(25);
        signInPane.setRoundTopRight(25);

        signInLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInLabel.setText("Sign In");
        signInLabel.setToolTipText("");
        signInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout signInPaneLayout = new javax.swing.GroupLayout(signInPane);
        signInPane.setLayout(signInPaneLayout);
        signInPaneLayout.setHorizontalGroup(
            signInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(signInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
        );
        signInPaneLayout.setVerticalGroup(
            signInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(signInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        actionsPane.add(signInPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 340, 60));

        messageLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageLabel.setText("Dont't have an account?");
        messageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        actionsPane.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 20));

        signUpLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(189, 147, 249));
        signUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signUpLabel.setText("Sign up");
        signUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLabelMouseClicked(evt);
            }
        });
        actionsPane.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 110, 20));

        backgroundPane.add(actionsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseClicked
        FATHER.showView(MainFrame.SIGNIN_VIEW);
    }//GEN-LAST:event_signUpLabelMouseClicked

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
        FATHER.showView(MainFrame.RSPSW_VIEW);
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked

    private void signInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseClicked
        String email = userInputPane.getText();
        String password = passwordInputPane.getText();
        Usuario usuario = new Usuario.Builder()
                .correoElectronico(email)
                .contrasena(password)
                .build();

        try {
            USUARIO_SERVICE.iniciarSesion(usuario);
            FATHER.showView(MainFrame.HOME_DISCOVER_VIEW);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(FATHER,"email or password dont match with a real user","login error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signInLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPane;
    private javax.swing.JPanel backgroundPane;
    private javax.swing.JPanel dataPane;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel messageLabel;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel passwordInputPane;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel signInLabel;
    private com.mycompany.hiChatJpa.view.components.PanelRound signInPane;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel tittleLabel;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel userInputPane;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
