package com.mycompany.hiChatJpa.view.pages.login;

import com.mycompany.hiChatJpa.view.Controller;
import com.mycompany.hiChatJpa.view.components.TextFieldPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author gatog
 */
public class LoginPane extends javax.swing.JPanel {

    private final Controller controller;

    /**
     * Creates new form LoginPane
     *
     * @param controller
     */
    public LoginPane(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPane = new javax.swing.JPanel();
        tittleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        dataPane = new javax.swing.JPanel();
        userEmailLabel = new javax.swing.JLabel();
        userEmailTxt = new TextFieldPanel(TextFieldPanel.EMAIL_REGEX, "invalid type of email");
        userPasswordLabel = new javax.swing.JLabel();
        userPasswordTxt = new TextFieldPanel(TextFieldPanel.PASSWORD_REGEX, "invalid password format to looong");
        forgotPasswordLabel = new javax.swing.JLabel();
        actionsPane = new javax.swing.JPanel();
        signInPane = new com.mycompany.hiChatJpa.view.components.PanelRound();
        signInLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        signUpLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        backgroundPane.setBackground(new java.awt.Color(22, 16, 34));
        backgroundPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("HiChat!");
        backgroundPane.add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, -1));

        descriptionLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(204, 204, 204));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("Welcome to hichat get started or login to continue");
        backgroundPane.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 20));

        dataPane.setOpaque(false);
        dataPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userEmailLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        userEmailLabel.setForeground(new java.awt.Color(204, 204, 204));
        userEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userEmailLabel.setText("Email");
        dataPane.add(userEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 360, 20));

        userEmailTxt.setMessage("enter your email");
        dataPane.add(userEmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        userPasswordLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        userPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        userPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userPasswordLabel.setText("Password");
        dataPane.add(userPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 85, 360, 20));

        userPasswordTxt.setMessage("enter your password");
        dataPane.add(userPasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        forgotPasswordLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(189, 147, 249));
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forgotPasswordLabel.setText("forgot password? ");
        forgotPasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });
        dataPane.add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 130, 20));

        backgroundPane.add(dataPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 190));

        actionsPane.setOpaque(false);
        actionsPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInPane.setBackground(new java.awt.Color(108, 43, 238));
        signInPane.setRoundBottomLeft(25);
        signInPane.setRoundBottomRight(25);
        signInPane.setRoundTopLeft(25);
        signInPane.setRoundTopRight(25);

        signInLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInLabel.setText("Sign In");
        signInLabel.setToolTipText("");
        signInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout signInPaneLayout = new javax.swing.GroupLayout(signInPane);
        signInPane.setLayout(signInPaneLayout);
        signInPaneLayout.setHorizontalGroup(
            signInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        signInPaneLayout.setVerticalGroup(
            signInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(signInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        actionsPane.add(signInPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 340, 60));

        messageLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageLabel.setText("Dont't have an account?");
        messageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        actionsPane.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 20));

        signUpLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(189, 147, 249));
        signUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signUpLabel.setText("Sign up");
        signUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLabelMouseClicked(evt);
            }
        });
        actionsPane.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 110, 20));

        backgroundPane.add(actionsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseClicked
        controller.showSignin();
    }//GEN-LAST:event_signUpLabelMouseClicked

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
        controller.showRestorePassword();
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked

    private void signInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseClicked
        String email = userEmailTxt.getText();
        String password = userPasswordTxt.getText();

        if (email.trim().isEmpty() || email.equals(userEmailTxt.getDefaultString()) || userEmailTxt.isInvalidInput()) {
            JOptionPane.showMessageDialog(null, "email cant be empty", "input error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (password.trim().isEmpty() || password.equals(userPasswordTxt.getDefaultString()) || userPasswordTxt.isInvalidInput()) {
            JOptionPane.showMessageDialog(null, "password name cant be empty", "input error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        controller.finalizarLogin(email, password);
    }//GEN-LAST:event_signInLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPane;
    private javax.swing.JPanel backgroundPane;
    private javax.swing.JPanel dataPane;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel signInLabel;
    private com.mycompany.hiChatJpa.view.components.PanelRound signInPane;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel tittleLabel;
    private javax.swing.JLabel userEmailLabel;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel userEmailTxt;
    private javax.swing.JLabel userPasswordLabel;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel userPasswordTxt;
    // End of variables declaration//GEN-END:variables
}
