package com.mycompany.hiChatJpa.view.pages.restorePassword;

import com.mycompany.hiChatJpa.view.Controller;

/**
 *
 * @author gatog
 */
public class RestorePswUserPane extends javax.swing.JPanel {

    private Controller controller;

    /**
     * Creates new form SigninPane
     *
     * @param controller
     */
    public RestorePswUserPane(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPane = new javax.swing.JPanel();
        headerPane = new javax.swing.JPanel();
        tittleLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JLabel();
        stepsPane = new javax.swing.JPanel();
        coloredPane2 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        coloredPane3 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        coloredPane4 = new com.mycompany.hiChatJpa.view.components.PanelRound();
        stepIndicatorLabel = new javax.swing.JLabel();
        findUserLabel = new javax.swing.JLabel();
        dataPane = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        textFieldPanel1 = new com.mycompany.hiChatJpa.view.components.TextFieldPanel();
        continuePane = new com.mycompany.hiChatJpa.view.components.PanelRound();
        continueLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        logInLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 600));

        backgroundPane.setBackground(new java.awt.Color(22, 16, 34));

        headerPane.setBackground(new java.awt.Color(51, 153, 255));
        headerPane.setOpaque(false);
        headerPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tittleLabel.setText("HiChat!");
        headerPane.add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 18, 240, 20));

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purple-arrow-32px.png"))); // NOI18N
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });
        headerPane.add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 30));

        stepsPane.setBackground(new java.awt.Color(0, 0, 0));
        stepsPane.setOpaque(false);
        stepsPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coloredPane2.setBackground(new java.awt.Color(108, 43, 238));
        coloredPane2.setRoundBottomLeft(15);
        coloredPane2.setRoundBottomRight(15);
        coloredPane2.setRoundTopLeft(15);
        coloredPane2.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane2Layout = new javax.swing.GroupLayout(coloredPane2);
        coloredPane2.setLayout(coloredPane2Layout);
        coloredPane2Layout.setHorizontalGroup(
            coloredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane2Layout.setVerticalGroup(
            coloredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 40, 10));

        coloredPane3.setBackground(new java.awt.Color(47, 35, 72));
        coloredPane3.setRoundBottomLeft(15);
        coloredPane3.setRoundBottomRight(15);
        coloredPane3.setRoundTopLeft(15);
        coloredPane3.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane3Layout = new javax.swing.GroupLayout(coloredPane3);
        coloredPane3.setLayout(coloredPane3Layout);
        coloredPane3Layout.setHorizontalGroup(
            coloredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane3Layout.setVerticalGroup(
            coloredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 15, 40, 10));

        coloredPane4.setBackground(new java.awt.Color(47, 35, 72));
        coloredPane4.setRoundBottomLeft(15);
        coloredPane4.setRoundBottomRight(15);
        coloredPane4.setRoundTopLeft(15);
        coloredPane4.setRoundTopRight(15);

        javax.swing.GroupLayout coloredPane4Layout = new javax.swing.GroupLayout(coloredPane4);
        coloredPane4.setLayout(coloredPane4Layout);
        coloredPane4Layout.setHorizontalGroup(
            coloredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        coloredPane4Layout.setVerticalGroup(
            coloredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        stepsPane.add(coloredPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, 40, 10));

        stepIndicatorLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        stepIndicatorLabel.setForeground(new java.awt.Color(204, 204, 204));
        stepIndicatorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stepIndicatorLabel.setText("Step 1 of 3");
        stepsPane.add(stepIndicatorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 20));

        findUserLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        findUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        findUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        findUserLabel.setText("Find your user");

        dataPane.setBackground(new java.awt.Color(51, 0, 153));
        dataPane.setOpaque(false);
        dataPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel.setText("Email or Username");
        dataPane.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 360, 20));
        dataPane.add(textFieldPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        continuePane.setBackground(new java.awt.Color(108, 43, 238));
        continuePane.setRoundBottomLeft(25);
        continuePane.setRoundBottomRight(25);
        continuePane.setRoundTopLeft(25);
        continuePane.setRoundTopRight(25);

        continueLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        continueLabel.setForeground(new java.awt.Color(255, 255, 255));
        continueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continueLabel.setText("Continue");
        continueLabel.setToolTipText("");
        continueLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout continuePaneLayout = new javax.swing.GroupLayout(continuePane);
        continuePane.setLayout(continuePaneLayout);
        continuePaneLayout.setHorizontalGroup(
            continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(continueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );
        continuePaneLayout.setVerticalGroup(
            continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(continuePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(continueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        messageLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageLabel.setText("actualy i remember my password");
        messageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logInLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 16)); // NOI18N
        logInLabel.setForeground(new java.awt.Color(189, 147, 249));
        logInLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logInLabel.setText("Log In");
        logInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundPaneLayout = new javax.swing.GroupLayout(backgroundPane);
        backgroundPane.setLayout(backgroundPaneLayout);
        backgroundPaneLayout.setHorizontalGroup(
            backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPaneLayout.createSequentialGroup()
                .addGroup(backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stepsPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(findUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(backgroundPaneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(continuePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPaneLayout.createSequentialGroup()
                                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(dataPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPaneLayout.setVerticalGroup(
            backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPaneLayout.createSequentialGroup()
                .addComponent(headerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findUserLabel)
                .addGap(33, 33, 33)
                .addComponent(dataPane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(continuePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // login
    }//GEN-LAST:event_returnButtonMouseClicked

    private void logInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInLabelMouseClicked
        // login
    }//GEN-LAST:event_logInLabelMouseClicked

    private void continueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLabelMouseClicked
        // continuar
    }//GEN-LAST:event_continueLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPane;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane2;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane3;
    private com.mycompany.hiChatJpa.view.components.PanelRound coloredPane4;
    private javax.swing.JLabel continueLabel;
    private com.mycompany.hiChatJpa.view.components.PanelRound continuePane;
    private javax.swing.JPanel dataPane;
    private javax.swing.JLabel findUserLabel;
    private javax.swing.JPanel headerPane;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel returnButton;
    private javax.swing.JLabel stepIndicatorLabel;
    private javax.swing.JPanel stepsPane;
    private com.mycompany.hiChatJpa.view.components.TextFieldPanel textFieldPanel1;
    private javax.swing.JLabel tittleLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
