package com.mycompany.hiChatJpa.view.components;

import com.mycompany.hiChatJpa.dto.ChatConMensajesDTO;

/**
 *
 * @author gatog
 */
public class ChatRegistroPanel extends javax.swing.JPanel {

    private final ChatConMensajesDTO chat;
    
    /**
     * Creates new form MatchRegistroPanel
     * @param chat
     */
    public ChatRegistroPanel(ChatConMensajesDTO chat) {
        this.chat = chat;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new com.mycompany.hiChatJpa.view.components.PanelRound();
        numberLabel = new javax.swing.JLabel();
        tittleLabel = new javax.swing.JLabel();
        goPanel = new com.mycompany.hiChatJpa.view.components.PanelRound();
        goButton = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(22, 16, 34));
        backgroundPanel.setRoundBottomLeft(20);
        backgroundPanel.setRoundBottomRight(20);
        backgroundPanel.setRoundTopLeft(20);
        backgroundPanel.setRoundTopRight(20);
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        numberLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel.setText(chat.getIdChat().toString());
        backgroundPanel.add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        tittleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tittleLabel.setText(chat.getNombre());
        tittleLabel.setToolTipText("");
        backgroundPanel.add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 50));

        goPanel.setBackground(new java.awt.Color(0, 204, 51));
        goPanel.setRoundBottomLeft(10);
        goPanel.setRoundBottomRight(10);
        goPanel.setRoundTopLeft(10);
        goPanel.setRoundTopRight(10);
        goPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goButton.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        goButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goButton.setText("GO AND VIEW");
        goButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goButtonMouseClicked(evt);
            }
        });
        goPanel.add(goButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        backgroundPanel.add(goPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 110, 30));

        add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goButtonMouseClicked
        
    }//GEN-LAST:event_goButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.hiChatJpa.view.components.PanelRound backgroundPanel;
    private javax.swing.JLabel goButton;
    private com.mycompany.hiChatJpa.view.components.PanelRound goPanel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
}
