package com.mycompany.hiChatJpa.view.components;

import com.mycompany.hiChatJpa.dto.MatchDTO;

/**
 *
 * @author gatog
 */
public class MatchRegistroPanel extends javax.swing.JPanel {

    private final MatchDTO match;
    
    /**
     * Creates new form MatchRegistroPanel
     * @param match
     */
    public MatchRegistroPanel(MatchDTO match) {
        this.match = match;
        initComponents();
        
        deletePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new com.mycompany.hiChatJpa.view.components.PanelRound();
        numberLabel = new javax.swing.JLabel();
        tittleLabel = new javax.swing.JLabel();
        deletePanel = new com.mycompany.hiChatJpa.view.components.PanelRound();
        deleteButton = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(22, 16, 34));
        backgroundPanel.setRoundBottomLeft(20);
        backgroundPanel.setRoundBottomRight(20);
        backgroundPanel.setRoundTopLeft(20);
        backgroundPanel.setRoundTopRight(20);
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        numberLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel.setText(match.getIdMatch().toString());
        backgroundPanel.add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        tittleLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tittleLabel.setText(match.getUsuarioA().getNombre() + "  |  " + match.getUsuarioB().getNombre());
        tittleLabel.setToolTipText("");
        backgroundPanel.add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 50));

        deletePanel.setBackground(new java.awt.Color(255, 51, 51));
        deletePanel.setRoundBottomLeft(10);
        deletePanel.setRoundBottomRight(10);
        deletePanel.setRoundTopLeft(10);
        deletePanel.setRoundTopRight(10);
        deletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteButton.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        deleteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteButton.setText("CANCEL");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deletePanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        backgroundPanel.add(deletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 110, 30));

        add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        
    }//GEN-LAST:event_deleteButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.hiChatJpa.view.components.PanelRound backgroundPanel;
    private javax.swing.JLabel deleteButton;
    private com.mycompany.hiChatJpa.view.components.PanelRound deletePanel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
}
