package com.mycompany.hiChatJpa.view.components;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author gatog
 */
public class TextFieldPanel extends javax.swing.JPanel {

    public static final String EMAIL_REGEX = "^[a-zA-Z0-9._%+-]{1,25}@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    
    
    private String regex;
    private String errorMessage;
    private String message = "default message";

    /**
     * Creates new form TextFieldPanel
     */
    public TextFieldPanel() {
        initComponents();
    }

    public TextFieldPanel(String regex, String errorMessage) {
        this.regex = regex;
        this.errorMessage = errorMessage;
        initComponents();
        errorDescriptionLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPane = new com.mycompany.hiChatJpa.view.components.PanelRound();
        inputTxt = new javax.swing.JTextField();
        inputBorderPane = new com.mycompany.hiChatJpa.view.components.PanelRound();
        errorDescriptionLabel = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputPane.setBackground(new java.awt.Color(47, 35, 72));
        inputPane.setRequestFocusEnabled(false);
        inputPane.setRoundBottomLeft(20);
        inputPane.setRoundBottomRight(20);
        inputPane.setRoundTopLeft(20);
        inputPane.setRoundTopRight(20);
        inputPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputTxt.setBackground(new java.awt.Color(47, 35, 72));
        inputTxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        inputTxt.setForeground(new java.awt.Color(255, 255, 255));
        inputTxt.setText(this.message);
        inputTxt.setBorder(null);
        inputTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputTxtFocusLost(evt);
            }
        });
        inputPane.add(inputTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 40));

        add(inputPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 340, 40));

        inputBorderPane.setBackground(new java.awt.Color(47, 35, 72));
        inputBorderPane.setRoundBottomLeft(25);
        inputBorderPane.setRoundBottomRight(25);
        inputBorderPane.setRoundTopLeft(25);
        inputBorderPane.setRoundTopRight(25);

        javax.swing.GroupLayout inputBorderPaneLayout = new javax.swing.GroupLayout(inputBorderPane);
        inputBorderPane.setLayout(inputBorderPaneLayout);
        inputBorderPaneLayout.setHorizontalGroup(
            inputBorderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        inputBorderPaneLayout.setVerticalGroup(
            inputBorderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        add(inputBorderPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 344, 44));

        errorDescriptionLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        errorDescriptionLabel.setForeground(new java.awt.Color(239, 68, 68));
        errorDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorDescriptionLabel.setText(this.errorMessage);
        add(errorDescriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void inputTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTxtFocusGained
        this.inputBorderPane.setBackground(Color.WHITE);
        if (inputTxt.getText().equals(message)) {
            inputTxt.setText("");
        }
    }//GEN-LAST:event_inputTxtFocusGained

    private void inputTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTxtFocusLost
        this.inputBorderPane.setBackground(Color.BLACK);
        String input = inputTxt.getText();
        if (input.isEmpty()) {
            inputTxt.setText(message);
        } else {
            if (this.regex != null) {
                Pattern pattern = Pattern.compile(this.regex);
                Matcher matcher = pattern.matcher(input);
                if (matcher.matches()) {
                    errorDescriptionLabel.setVisible(false);
                }else {
                    this.inputBorderPane.setBackground(Color.RED);
                    errorDescriptionLabel.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_inputTxtFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorDescriptionLabel;
    private com.mycompany.hiChatJpa.view.components.PanelRound inputBorderPane;
    private com.mycompany.hiChatJpa.view.components.PanelRound inputPane;
    private javax.swing.JTextField inputTxt;
    // End of variables declaration//GEN-END:variables

    public void setMessage(String message) {
        this.message = message;
        this.inputTxt.setText(message);
    }
}
